%YAML:1.0
calib_file_left: /home/h/Catkin/sineva_elas/src/sineva_elas/config/calib_left.yml
calib_file_right: /home/h/Catkin/sineva_elas/src/sineva_elas/config/calib_right.yml
baseline: 0.119170950703722
